export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
export const FILTER_TASK = 'FILTER_TASK';
export const FILTER_TASK_SUCCESS = 'FILTER_TASK_SUCCESS';
